---
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.24.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$  # Specify file types to be linted
        args: ['--fix']  # Automatically fix issues if possible
